"""Governed knowledge domain: structured metrics, glossary, holdout isolation."""

from queryforge.domain.knowledge.governance import (
    CONTENT_VERSION_LENGTH,
    DEFAULT_HOLDOUT_OVERLAP_RATIO,
    GlossaryEntry,
    GovernedDocument,
    HoldoutContaminationError,
    HoldoutEntry,
    HoldoutRegistry,
    KnowledgeGovernanceError,
    KnowledgeResolution,
    KnowledgeSource,
    MetricKnowledgeEntry,
    SqlExampleDecision,
    SqlExampleGovernance,
    StructuredKnowledgeBase,
    VerificationLevel,
    classify_sql_example,
    content_hash,
    content_version,
    is_trusted_for_examples,
    normalize_term,
    verification_level_of,
)

__all__ = [
    "CONTENT_VERSION_LENGTH",
    "DEFAULT_HOLDOUT_OVERLAP_RATIO",
    "GlossaryEntry",
    "GovernedDocument",
    "HoldoutContaminationError",
    "HoldoutEntry",
    "HoldoutRegistry",
    "KnowledgeGovernanceError",
    "KnowledgeResolution",
    "KnowledgeSource",
    "MetricKnowledgeEntry",
    "SqlExampleDecision",
    "SqlExampleGovernance",
    "StructuredKnowledgeBase",
    "VerificationLevel",
    "classify_sql_example",
    "content_hash",
    "content_version",
    "is_trusted_for_examples",
    "normalize_term",
    "verification_level_of",
]
